// <auto-generated />
namespace Sample.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Account_Add_Phone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Account_Add_Phone));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141529519_Account_Add_Phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
